# -*- coding: utf-8 -*-
"""Butterfly_stages_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HuaMxEDW826-yYeiby9IgWf_O3aV0zl_
"""

pip install tensorflowjs

#Importing Libraries
import os
import numpy as np

import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.image import load_img, ImageDataGenerator
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Dropout, Flatten

# from google.colab import drive
# drive.mount('/content/drive')

# data_dir='/content/drive/MyDrive/butterflyml/Butterfly/butterfly_photos/'
# print(data_dir)
data_dir='./butterfly_photos/butterfly'
print(data_dir)

data_dir=tf.keras.preprocessing.image_dataset_from_directory(data_dir)

count = 0
dirs = os.listdir('./butterfly_photos/butterfly/')
for dir in dirs:
    files = list(os.listdir('./butterfly_photos/butterfly/'+dir))
    print( dir +' Folder has '+ str(len(files)) + './butterfly_photos/butterfly/')
    count = count + len(files)
print( 'Images Folder has '+ str(count) + './butterfly_photos/butterfly/')

base_dir = './butterfly_photos/butterfly/'
img_size = 180
batch = 32

train_ds = tf.keras.utils.image_dataset_from_directory( base_dir,
                                                       seed = 123,
                                                       validation_split=0.2,
                                                       subset = 'training',
                                                       batch_size=batch,
                                                       image_size=(img_size,img_size))

val_ds = tf.keras.utils.image_dataset_from_directory( base_dir,
                                                       seed = 123,
                                                       validation_split=0.2,
                                                       subset = 'validation',
                                                       batch_size=batch,
                                                       image_size=(img_size,img_size))

butterfly_names = train_ds.class_names
butterfly_names

import matplotlib.pyplot as plt

i = 0
plt.figure(figsize=(10,10))

for images, labels in train_ds.take(1):
    for i in range(9):
        plt.subplot(3,3, i+1)
        plt.imshow(images[i].numpy().astype('uint8'))
        plt.title(butterfly_names[labels[i]])
        plt.axis('off')

AUTOTUNE = tf.data.AUTOTUNE

train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size = AUTOTUNE)

val_ds = val_ds.cache().prefetch(buffer_size = AUTOTUNE)

"""##Data AUgmentation"""

data_augmentation = Sequential([
    layers.RandomFlip("horizontal", input_shape = (img_size,img_size,3)),
    layers.RandomRotation(0.1),
    layers.RandomZoom(0.1)
])

i = 0
plt.figure(figsize=(10,10))

for images, labels in train_ds.take(1):
    for i in range(9):
        images = data_augmentation(images)
        plt.subplot(3,3, i+1)
        plt.imshow(images[0].numpy().astype('uint8'))
        plt.axis('off')

"""##Model Creation"""

model = Sequential([
    data_augmentation,
    layers.Rescaling(1./255),
    Conv2D(16, 3, padding='same', activation='relu'),
    MaxPooling2D(),
    Conv2D(32, 3, padding='same', activation='relu'),
    MaxPooling2D(),
    Conv2D(64, 3, padding='same', activation='relu'),
    MaxPooling2D(),
    Dropout(0.2),
    Flatten(),
    Dense(128, activation='relu'),
    Dense(18)
])

model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])



model.summary()

history = model.fit(train_ds, epochs=15, validation_data=val_ds)

def classify_images(image_path):
    input_image = tf.keras.utils.load_img(image_path, target_size=(180,180))
    input_image_array = tf.keras.utils.img_to_array(input_image)
    input_image_exp_dim = tf.expand_dims(input_image_array,0)

    predictions = model.predict(input_image_exp_dim)
    result = tf.nn.softmax(predictions[0])
    outcome = 'The Image belongs to ' + butterfly_names[np.argmax(result)] + ' with a score of '+ str(np.max(result)*100)
    return outcome

classify_images('./butterfly_photos/butterfly/Butterfly-Emerald Swallowtail/Emerald Swallowtail 8.jpg')

model.save('./butterfly_photos/ButterflyRecog_Stages_Model.keras')

model.save('./butterfly_photos/Butterfly_Stages_Model.h5')
